package in.gov.jci.hrms.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * One (movement, pay-month) row of what PayrollComputationService's monthly run needs to apply a
 * mid-cycle transfer: the releasing/receiving office day-split, revised HRA tier, and payable
 * transit-JT vs. deductible transit-LWP days. Generated by PayrollMovementIntegrationService when
 * a joining report is approved; is_payroll_applied flips true once an actual payroll run has
 * consumed it (that consumption itself is a follow-on wiring into PayrollComputationService, out
 * of scope here - this table is the carrier, ready for that service to read).
 */
@Entity
@Table(name = "payroll_movement_inputs")
public class PayrollMovementInput {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "movement_id", nullable = false)
    private EmployeeMovementRecord movement;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "employee_id", nullable = false)
    private Employee employee;

    @Column(name = "pay_month", nullable = false)
    private int payMonth;

    @Column(name = "pay_year", nullable = false)
    private int payYear;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "releasing_office_id")
    private RegionalOffice releasingOffice;

    @Column(name = "releasing_office_days", nullable = false)
    private int releasingOfficeDays;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "receiving_office_id")
    private RegionalOffice receivingOffice;

    @Column(name = "receiving_office_days", nullable = false)
    private int receivingOfficeDays;

    @Column(name = "revised_basic_pay", precision = 12, scale = 2)
    private BigDecimal revisedBasicPay;

    @Enumerated(EnumType.STRING)
    @Column(name = "revised_hra_tier", length = 10)
    private CityClass revisedHraTier;

    @Column(name = "transit_jt_days", nullable = false)
    private int transitJtDays;

    @Column(name = "transit_lwp_days", nullable = false)
    private int transitLwpDays;

    @Column(name = "is_payroll_applied", nullable = false)
    private boolean payrollApplied = false;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected PayrollMovementInput() {
    }

    public PayrollMovementInput(EmployeeMovementRecord movement, Employee employee, int payMonth, int payYear) {
        this.movement = movement;
        this.employee = employee;
        this.payMonth = payMonth;
        this.payYear = payYear;
    }

    public Long getId() {
        return id;
    }

    public EmployeeMovementRecord getMovement() {
        return movement;
    }

    public Employee getEmployee() {
        return employee;
    }

    public int getPayMonth() {
        return payMonth;
    }

    public int getPayYear() {
        return payYear;
    }

    public RegionalOffice getReleasingOffice() {
        return releasingOffice;
    }

    public void setReleasingOffice(RegionalOffice releasingOffice) {
        this.releasingOffice = releasingOffice;
    }

    public int getReleasingOfficeDays() {
        return releasingOfficeDays;
    }

    public void setReleasingOfficeDays(int releasingOfficeDays) {
        this.releasingOfficeDays = releasingOfficeDays;
    }

    public RegionalOffice getReceivingOffice() {
        return receivingOffice;
    }

    public void setReceivingOffice(RegionalOffice receivingOffice) {
        this.receivingOffice = receivingOffice;
    }

    public int getReceivingOfficeDays() {
        return receivingOfficeDays;
    }

    public void setReceivingOfficeDays(int receivingOfficeDays) {
        this.receivingOfficeDays = receivingOfficeDays;
    }

    public BigDecimal getRevisedBasicPay() {
        return revisedBasicPay;
    }

    public void setRevisedBasicPay(BigDecimal revisedBasicPay) {
        this.revisedBasicPay = revisedBasicPay;
    }

    public CityClass getRevisedHraTier() {
        return revisedHraTier;
    }

    public void setRevisedHraTier(CityClass revisedHraTier) {
        this.revisedHraTier = revisedHraTier;
    }

    public int getTransitJtDays() {
        return transitJtDays;
    }

    public void setTransitJtDays(int transitJtDays) {
        this.transitJtDays = transitJtDays;
    }

    public int getTransitLwpDays() {
        return transitLwpDays;
    }

    public void setTransitLwpDays(int transitLwpDays) {
        this.transitLwpDays = transitLwpDays;
    }

    public boolean isPayrollApplied() {
        return payrollApplied;
    }

    public void setPayrollApplied(boolean payrollApplied) {
        this.payrollApplied = payrollApplied;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
